apiVersion: v1
kind: Pod
metadata:
  name: gosdk-benchmark
spec:
  restartPolicy: Never
  nodeSelector:
    cloud.google.com/gke-tpu-topology: 2x2
    cloud.google.com/gke-tpu-accelerator: tpu-v6e-slice
  containers:
  - name: gosdk-benchmark
    image: us-east5-docker.pkg.dev/tpu-prod-env-automated/kislayk/gosdk-benchmark:latest
    command: ["/app"]
    args: ["--warm-up-time", "1m", "--run-time", "2m", "--worker", "128", "--bucket", "kislayk_fio_east5" ,"--client-protocol", "grpc"]
  serviceAccountName: default