apiVersion: v1
kind: Pod
metadata:
  name: gosdk-benchmark
spec:
  restartPolicy: Never
  nodeSelector:
    cloud.google.com/gke-tpu-topology: 2x2
    cloud.google.com/gke-tpu-accelerator: tpu-v6e-slice
  containers:
  - name: gosdk-benchmark
    image: $REGION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/gosdk-benchmark:latest
    command: ["/app"]
    args: ["--warm-up-time", "2m", "--run-time", "5m", "--worker", "128", "--bucket", "$BUCKET_NAME" ,"--client-protocol", "$PROTOCOL"]
  serviceAccountName: default
